/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDiscordInteractionsRouteImport } from './routes/api/public/discord/interactions'
import { Route as ApiPublicDiscordPanelRouteImport } from './routes/api/public/discord/panel'
import { Route as ApiPublicDiscordRegisterRouteImport } from './routes/api/public/discord/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordInteractionsRoute =
  ApiPublicDiscordInteractionsRouteImport.update({
    id: '/api/public/discord/interactions',
    path: '/api/public/discord/interactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscordPanelRoute = ApiPublicDiscordPanelRouteImport.update({
  id: '/api/public/discord/panel',
  path: '/api/public/discord/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordRegisterRoute =
  ApiPublicDiscordRegisterRouteImport.update({
    id: '/api/public/discord/register',
    path: '/api/public/discord/register',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/discord/panel': typeof ApiPublicDiscordPanelRoute
  '/api/public/discord/register': typeof ApiPublicDiscordRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/discord/panel': typeof ApiPublicDiscordPanelRoute
  '/api/public/discord/register': typeof ApiPublicDiscordRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/discord/panel': typeof ApiPublicDiscordPanelRoute
  '/api/public/discord/register': typeof ApiPublicDiscordRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/discord/interactions'
    | '/api/public/discord/panel'
    | '/api/public/discord/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/discord/interactions'
    | '/api/public/discord/panel'
    | '/api/public/discord/register'
  id:
    | '__root__'
    | '/'
    | '/api/public/discord/interactions'
    | '/api/public/discord/panel'
    | '/api/public/discord/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDiscordInteractionsRoute: typeof ApiPublicDiscordInteractionsRoute
  ApiPublicDiscordPanelRoute: typeof ApiPublicDiscordPanelRoute
  ApiPublicDiscordRegisterRoute: typeof ApiPublicDiscordRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/interactions': {
      id: '/api/public/discord/interactions'
      path: '/api/public/discord/interactions'
      fullPath: '/api/public/discord/interactions'
      preLoaderRoute: typeof ApiPublicDiscordInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/panel': {
      id: '/api/public/discord/panel'
      path: '/api/public/discord/panel'
      fullPath: '/api/public/discord/panel'
      preLoaderRoute: typeof ApiPublicDiscordPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/register': {
      id: '/api/public/discord/register'
      path: '/api/public/discord/register'
      fullPath: '/api/public/discord/register'
      preLoaderRoute: typeof ApiPublicDiscordRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDiscordInteractionsRoute: ApiPublicDiscordInteractionsRoute,
  ApiPublicDiscordPanelRoute: ApiPublicDiscordPanelRoute,
  ApiPublicDiscordRegisterRoute: ApiPublicDiscordRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
